apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  finalizers:
  - routes.serving.knative.dev
  name: tanzu-java-web-app-staging
  namespace: default
spec:
  traffic:
  - configurationName: tanzu-java-web-app
    percent: 100
    tag: staging