apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: unicorn-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: unicorn-app
spec:
  params:
    - name: run-image
      value: harbor-repo.vmware.com/tapsme/supply-chain/unicorn-app
  source:
    git:
      url: https://github.com/Mpluya/tanzu-java-web-app
      ref:
        branch: main
